#!/bin/bash


apt-get install default-jre -y
apt-get install default-jdk -y
apt-get install curl -y
mkdir /opt/jmeter
cd /opt/jmeter
wget http://mirrors.estointernet.in/apache//jmeter/binaries/apache-jmeter-5.1.1.zip
unzip apache-jmeter-5.1.1.zip
apt-get update -y
apt-get install -y unzip xvfb libxi6 libgconf-2-4 -y
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
chmod +x google-chrome-stable_current_amd64.deb
dpkg -i google-chrome-stable_current_amd64.deb
wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
unzip chromedriver_linux64.zip
mv chromedriver /usr/bin/chromedriver
sudo chown root:root /usr/bin/chromedriver
chmod +x /usr/bin/chromedriver
cd /opt/jmeter/apache-jmeter-5.1.1
wget https://jmeter-plugins.org/files/packages/jpgc-webdriver-3.0.zip
unzip jpgc-webdriver-3.0.zip
sudo sh /opt/jmeter/apache-jmeter-5.1.1/bin/jmeter.sh



